name: Update composer deps

on:
  push:
    branches:
    - main

  schedule:
  - cron: '0 2 * * *'

  pull_request:

env:
  GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

jobs:
  update-composer-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        command: update --lock
    - name: Commit changes
      run: |
        git config --global user.name "${GIT_USER_EMAIL}"
        git config --global user.email "${GIT_USER_EMAIL}"   
        
        if [[! $(git diff --exit-code composer.lock) ]]; then
          git commit -m "Update composer dependencies" composer.lock
          git push
        else
          echo "No changes detected"
        fi

