name: Update composer deps

on:
  push:
    branches:
    - main

  schedule:
  - cron: '0 2 * * *'

  pull_request:

jobs:
  update-composer-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - name: Update lock file
      uses: php-actions/composer@v6
      with:
        command: update --lock
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update lock file
        file_pattern: 'composer.lock'
